### ISSUE TITLE
Import 'styles.css' files instead of 'styles.scss' in components.

### ISSUE THREAD

**Issue by radu-iosif-moldovan** [muresanandrei1/react-comp-generator#1]
You should import the '.css' files in the react components. Rookie mistake 👎

**Comment by muresanandrei1** [comment]
I am very sorry this happend, was exhausted when I added this new functionality, I hope you didn't waste much time removing an "s" from the import, it is indeed frustrating to use the keyboard, pushing a fix right now :100:

**Comment by muresanandrei1** [comment]
https://github.com/muresanandrei1/react-comp-generator/commit/eab54be72f3edf48dac6a65036deed9889b4d8b4
